config/routes.rb
Rails.application.routes.draw do
  resources :courses do 
    member do
      get :roll
    end 
  end 
  resources :students do
    resources :awards
    member do 
      get :courses 
      post :course_add
      post :course_remove
    end 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
    belongs_to :student
    validates_associated :student
    validates_presence_of :name, :year
    
    validates_uniqueness_of :name, scope: :year, message: "already been given for that year"
    
    validates_inclusion_of :year, in: (1980..Date.today.year)
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :students
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :awards, dependent: :destroy
    has_and_belongs_to_many :courses
    
    def name
        given_name + " " + family_name
    end
    
    def enrolled_in?(course)
        self.courses.include?(course)
    end
    
    def unenrolled_courses
        Course.all - self.courses
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :get_student
  before_action :set_award, only: [:show, :edit, :update, :destroy]

  # GET /awards
  # GET /awards.json
  def index
    @awards = @student.awards
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
  end

  # GET /awards/new
  def new
    @award = @student.awards.build
  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = @student.awards.build(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url, notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_student
      @student = Student.find(params[:student_id])
    end
    
    def set_award
      @award = @student.awards.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :year, :student_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def roll
    @course = Course.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def courses 
    @student = Student.find(params[:id])
    @courses = @student.courses
  end
  
  def course_add
    @student = Student.find(params[:id])
    @course = Course.find(params[:id])
    
    unless @student.enrolled_in?(@course)
    @student.courses << @course
    flash[:notice] = 'Student was successfully enrolled'
  else
    flash[:error] = 'Student was already enrolled'
  end
  
  redirect_to action: "courses", id: @student
end

  def course_remove
    @student = Student.find(params[:id])
    
    course_ids = params[:courses]
    
    if course_ids.any?
      course_ids.each do |course_id|
        course = Course.find(course_id)
        if @student.enrolled_in?(course)
          logger.info "Removing student from course #{course.id}"
          @student.courses.delete(course)
          flash[:notice] = Course was successfully deleted
        end
      end
    end 
    redirect_to action: "courses", id: @student
  end 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:given_name, :middle_name, :family_name, :date_of_birth, :grade_point_average, :start_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/application/_navigation.html.erb
<p>
    <%= link_to "Students", students_path %> |
    <%= link_to "Courses", courses_path %>
</p>

app/views/awards/_form.html.erb
<%= form_for([@student, award]) do |form| %>
  <% if award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing Award for <$= @student.name %></h1>

<%= render 'form', award: @award %>

<%= link_to 'Show', [(@student, @award] %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Awards for <%= @student.name %></h1>

<% if !@student.awards.empty? %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awards.each do |award| %>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.year %></td>
        <td><%= award.student.given_name %><%= award.student.family_name %></td>
        <td><%= link_to 'Show', [ @student, award] %></td>
        <td><%= link_to 'Edit', edit_student_award_path(@student, award) %></td>
        <td><%= link_to 'Awards', student_awards_path(@student) %></td>
        <td><%= link_to 'Destroy', [ @student, award], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% else %>
<p><%= @student.given_name %> hasn't won any awards yet.</p>
<% end %>


<%= link_to 'New Award', new_student_award_path(@student) %> |
<%= link_to 'Back', @student %>

app/views/awards/new.html.erb
<h1>New Award for <%= @student.name %></h1>

<%= render 'form', award: @award %>

<%= link_to 'Back', student_awards_path(@student)  %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @award.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @award.year %>
</p>

<p>
  <strong>Student:</strong>
  <%= @award.student.given_name %><%= @award.student.family_name %>
</p>

<%= link_to 'Edit', edit_student_award_path(@student, @award) %> |
<%= link_to 'Awards', student_awards_path(@student) %> |
<%= link_to 'Back', student_awards_path(@student) %>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/roll.html.erb
<h1>Roll for <%= @course.name %></h1>
<% if @course.students.count > 0 %>
<table>
    <thead>
        <tr>
            <th>Student</th>
            <th>GPA</th>
        </tr>
    </thead>
    </tbody>
    <% @course.students.each do |student| %>
    <tr>
        <td><%= link_to student.name, student %></td>
        <td><%= student.grade_point_average %></td>
    </tr>
    <% end %>
    </tbody>
</table>
<% else %>
<p>No students are enrolled</p>
<% end %>
<p><%= link_to 'Back', @course %></p>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Roll', roll_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "navigation" %>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :given_name %>
    <%= form.text_field :given_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="field">
    <%= form.label :family_name %>
    <%= form.text_field :family_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :grade_point_average %>
    <%= form.text_field :grade_point_average %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/courses.html.erb
<h1><%= @student.name %>'s courses</h1>
<% if @courses.length > 0 %>
<%= form_tag(course_remove_student_path(@student)) do %>
<table>
    <thead>
        <tr>
            <th>Course</th>
            <th>Remove?</th>
        </tr>
    </thead>
    
    <tbody>
        <% for course in @courses do %>
        <tr>
            <td><%= course.name %></td>
            <td><%= check_box_tag "courses[]", course.id %></td>
        </tr>
        <% end %>
        </tbody>
        </table>
        <br />
        
        <%= submit_tag 'Remove checked courses' %>
        <% end %>
        <% else %>
        <p>Not enrolled in any courses yet.</p>
        <% end %>
        
        <h2>Enroll in new course</h2>
        
        <% if @student.courses.count < Course.count then %>
        <%= form_tag(course_add_student_path(@student)) do %>
        <%= select_tag(:course, options_from_collection_for_select(@student.unenrolled_courses, :id, :name)) %>
        <%= submit_tag 'Enroll' %>
        <% end %>
        <% else %>
        <p><%= @student.name %> is enrolled in every course.</p>
        <% end %>
        <p><%=link_to 'Back', @student %></p>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Awards</th>
      <th>Given name</th>
      <th>Middle name</th>
      <th>Family name</th>
      <th>Date of birth</th>
      <th>Grade point average</th>
      <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.given_name %></td>
        <td><%= student.middle_name %></td>
        <td><%= student.family_name %></td>
        <td><%= student.date_of_birth %></td>
        <td><%= student.grade_point_average %></td>
        <td><%= student.start_date %></td>
        <td><%= student.awards.count %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Given name:</strong>
  <%= @student.given_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @student.middle_name %>
</p>

<p>
  <strong>Family name:</strong>
  <%= @student.family_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @student.date_of_birth %>
</p>

<p>
  <strong>Grade point average:</strong>
  <%= @student.grade_point_average %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @student.start_date %>
</p>

<p>
  <strong>Courses:</strong>
  <% if !@student.courses.empty? %>
  <%= @student.courses.collect {|c| link_to(c.name, c)}.join(",").html_safe %>
  <% else %>
  Not enrolled on any courses yet.
  <% end %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Courses', courses_student_path(@student) %> |
<%= link_to 'Awards', student_awards_path(@student) %> |
<%= link_to 'Back', students_path %>